version: "3.11"
services:
  hangman_app:
    container_name: hangman
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - SERVER_HOST=https://localhost
      - PROJECT_NAME=Hangman
      - SECRET_KEY=7e00696cd12d5df1dea20f5056a5f47e
    ports:
      - "8000:8000"
    networks:
      - development
    volumes:
      - .:/app

networks:
  development:
